version: "3.8"

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    hostname: mariadb
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /opt/docker/mariadb/mysql:/var/lib/mysql
      - /opt/docker/mariadb/conf/conf.d:/etc/mysql/conf.d:ro
    networks: 
      - productive_data     
      - productive_web
    env_file:
      - .env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=200M
    networks:
      - productive_data
      - productive_web

networks:
  productive_data:
    external: true
  productive_web:
    external: true
