services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - ./config/jellyfin:/config
      - ./cache/jellyfin:/cache
      - ./media/movies:/data/movies
      - ./media/tv:/data/tv
    environment:
      - TZ=Europe/Berlin
    networks:
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - media_network

  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=192.168.178.0/24
      - NAME_SERVERS=1.1.1.1,8.8.8.8
      - TZ=Europe/Vienna
      - PUID=1000
      - PGID=1000
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=adminadmin
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
      - ./openvpn:/config/openvpn
    restart: unless-stopped
    networks:
      - media_network
      
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - media_network
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - media_network

networks:
  media_network:
    driver: bridge