version: '3.8'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - /media:/data
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config
      - /media:/data
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    ports:
      - 8085:8080
    volumes:
      - ./config/sabnzbd:/config
      - /media/downloads:/data/downloads
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
    volumes:
      - ./config/jellyseerr:/app/config
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    ports:
      - "8265:8265"
      - "8266:8266"
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/tdarr/server:/app/server
      - ./config/tdarr/configs:/app/configs
      - ./config/tdarr/logs:/app/logs
      - /media:/data
      - /opt/docker/media-docker/temp/tdarr-cache:/temp
    restart: unless-stopped

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    depends_on:
      - tdarr
    environment:
      - TZ=Europe/Berlin
      - serverIP=tdarr
      - serverPort=8266
      - nodeName=Node-1
      - nodeID=CPU-Node-1
    volumes:
      - ./config/tdarr/configs:/app/configs
      - ./config/tdarr/logs:/app/logs
      - /media:/data
      - /opt/docker/media-docker/temp/tdarr-cache:/temp
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
